from Ecommerce.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('login/register/', views.Register, name='register'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('product/<str:product_slugs>/', views.productdetail, name='productdetail'),
    path('addtocart/<int:pid>/<str:loc>', views.Addtocarts, name='addtocart'),
    path('cart/', views.cart, name='cart'),
    path('<int:rpid>/remove-product', views.Remove_cart_product, name="remove-product"),
    path('update-cart/<int:pids>/<str:sign>/', views.updatecart, name='update-cart'),
    path('index/', views.home, name='index'),
    path('checkout/<str:order_from>/', views.Checkout, name='checkout'),
    path('getcurrentlocation/<str:order_from>/', views.User_current_location, name='getcurrentlocation'),
    path('save-deliver-address/', views.SaveDeliverAddress, name='save-deliver-address'),
    path('select-deliver-address/<int:delid>/<str:order_from>/', views.SelectDeliverAddress, name='select-deliver-address'),
    path('order/<str:from_order>/<int:delid>', views.Orders, name='order'),
    path('myorders/', views.MyOrders, name='myorders'),
    path('order-information/<int:oid>/', views.OrderInformation, name='orderinformation'),
    path('handlerequest/<str:order_type>/', views.Handlerequest, name='handlerequest'),
    path('contact-us/', views.ContactUs, name='contact-us'),
    path('about-us/', views.AboutUs, name='about-us'),
    path('addtowishlist/<int:pid>/', views.AddtoWishlist, name='addtowishlist'),
    path('displaywishlist/', views.DisplayWishlist, name='displaywishlist'),
    path('myprofile/', views.MyProfile, name='myprofile'),
    path('updateprofile/', views.UpdateProfile, name='updateprofile'),
    path('searchproductpage/', views.Searchproductpage, name='searchproductpage'),
    path('getsuggest', views.Getsuggest, name='getsuggest'),
    path('category-related-products/<str:cid>/', views.Crt, name='crt'),
    path('complaints/', views.Complaints, name='complaints'),
    path('verifyotp/<str:en_email>/<str:otptype>/<str:en_otp>/', views.VerifyOTP, name='verifyotp'),
    path('forgot-password/', views.ForgotPassword, name='forgot-password'),
    path('sendotp/', views.SendOTP, name='sendotp'),
    path('newpassword/<str:en_email>/', views.NewPassword, name='newpassword'),
]
