# Generated by Django 4.2 on 2023-04-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('brands_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brands_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='main_category',
            fields=[
                ('main_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('sub_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('sizes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sizes_name', models.CharField(max_length=50)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.brands')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.category')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('products_id', models.IntegerField(primary_key=True, serialize=False)),
                ('products_name', models.CharField(max_length=50)),
                ('products_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField(max_length=500)),
                ('product_image_first', models.ImageField(max_length=255, upload_to='media')),
                ('product_image_second', models.ImageField(max_length=255, upload_to='media')),
                ('product_image_third', models.ImageField(max_length=255, upload_to='media')),
                ('product_image_fourth', models.ImageField(max_length=255, upload_to='media')),
                ('product_image_fifth', models.ImageField(max_length=255, upload_to='media')),
                ('free_delivery', models.BooleanField()),
                ('cash_on_delivery', models.BooleanField()),
                ('product_return', models.BooleanField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.brands')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.category')),
                ('sizes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.sizes')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='product_size_quantity',
            fields=[
                ('product_size_quantity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('size_quantity', models.CharField(max_length=50)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.products')),
                ('sizes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.sizes')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.main_category'),
        ),
    ]
