# Generated by Django 4.2 on 2023-04-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brands',
            new_name='brand',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
        migrations.RenameModel(
            old_name='sizes',
            new_name='size',
        ),
    ]
