# Generated by Django 4.2 on 2023-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0002_rename_brands_brand_rename_products_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_fifth',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_first',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_fourth',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_second',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_third',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
    ]
