# Generated by Django 4.2 on 2023-04-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0003_alter_product_product_image_fifth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.CharField(default='30%', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='products_title',
            field=models.CharField(default='nice', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_fifth',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_first',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_fourth',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_second',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_third',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
