# Generated by Django 4.2 on 2023-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0004_product_product_discount_product_products_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='blog', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_title',
            field=models.CharField(max_length=50),
        ),
    ]
