# Generated by Django 4.2 on 2023-04-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0009_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='user_id',
        ),
    ]
