# Generated by Django 4.2 on 2023-04-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0011_remove_product_sizes_id_size_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.product'),
        ),
    ]
