# Generated by Django 4.2 on 2023-04-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0012_alter_size_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Electronics_Ecommerce.main_category'),
        ),
    ]
