# Generated by Django 4.2 on 2023-05-04 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0014_addtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
