# Generated by Django 4.2 on 2023-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0015_addtocart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
