# Generated by Django 4.2 on 2023-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0017_addtocart_total_addtocart_total_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_review',
            field=models.DecimalField(decimal_places='1', editable=False, max_digits='10', null=True),
        ),
    ]
