# Generated by Django 4.2 on 2023-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0018_product_average_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_review',
        ),
        migrations.AddField(
            model_name='product',
            name='product_average',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=3, null=True),
        ),
    ]
