# Generated by Django 4.2 on 2023-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0020_product_no_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_average',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
