# Generated by Django 4.2.1 on 2023-05-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0021_alter_product_product_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_average',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=3, null=True),
        ),
    ]
