# Generated by Django 4.2.1 on 2023-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0022_alter_product_product_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='images/img1.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='main_category',
            name='main_category_image',
            field=models.ImageField(default='images/img1.jpg', upload_to='images'),
        ),
    ]
