# Generated by Django 4.2.1 on 2023-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0023_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='nothing', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_rated_product',
            field=models.BooleanField(default=False),
        ),
    ]
