# Generated by Django 4.2.1 on 2023-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0025_deliveraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_alternative_mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_pincode',
            field=models.IntegerField(null=True),
        ),
    ]
