# Generated by Django 4.2.1 on 2023-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0026_alter_deliveraddress_deliver_alternative_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_alternative_mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
