# Generated by Django 4.2.1 on 2023-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0031_remove_deliveraddress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveraddress',
            name='deliver_address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
