# Generated by Django 4.2.1 on 2023-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0035_order_amount_order_amount_currency_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
