# Generated by Django 4.2.1 on 2023-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0036_order_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='Image_slider')),
                ('slider_text', models.CharField(max_length=100)),
            ],
        ),
    ]
