# Generated by Django 4.2.1 on 2023-06-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0040_remove_order_transaction_id_order_razpory_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_of_order',
            field=models.IntegerField(default=0),
        ),
    ]
