# Generated by Django 4.2.1 on 2023-07-15 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0045_profile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_of_order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
