# Generated by Django 4.2.1 on 2023-08-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_Ecommerce', '0046_remove_order_id_of_order_order_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
